force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <displayFormat>ITM-{000000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Current_Borrower__c.field-meta.xml
<CustomField>
    <fullName>Current_Borrower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Borrower</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Borrowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BorrowingHistoryHelper.cls
/**
@Name			:		BorrowingHistoryHelper
@Date			:		13 Oct 2019
@Description	:		Trigger Helper to update item if return date is not null
@Developer		:		Nitin Chandwani
*/
public class BorrowingHistoryHelper {
    
    //Mark all associated Items as available
    public static void updateItems( Set<Id> itemIds ){
        if( itemIds != NULL && itemIds.size() > 0 ){
            List<Item__c> items = new List<Item__c>();
            for( Item__c item : getItems( itemIds ) ){
                item.Status__c = 'Available';
                item.Current_Borrower__c = NULL;
                items.add( item );
            }
            if( items != NULL && items.size() > 0 ){
                UPDATE items;
            }
        }
    }
    
    //Get Items
    private static List<Item__c> getItems( Set<Id> itemIds ){
        if( itemIds != NULL && itemIds.size() > 0 ){
            return [SELECT Id, Status__c FROM Item__c WHERE Id IN: itemIds ];
        }
        return NULL;
    }
}