force-app/main/default/objects/Borrowing_History__c/Borrowing_History__c.object-meta.xml
<CustomObject>
    <label>Borrowing History</label>
    <nameField>
        <displayFormat>BH-{00000}</displayFormat>
        <label>Borrowing History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Borrowing Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Borrowing_History__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Borrowing Histories</relationshipLabel>
    <relationshipName>Borrowing_Histories</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Borrowing_History__c/fields/Fine__c.field-meta.xml
<CustomField>
    <fullName>Fine__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fine(If Any)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Borrowing_History__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( ISNULL(Return_Date__c ), &#39;Borrowed&#39;, &#39;Returned&#39;)</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OverdueBatch.cls
/**
@Name			:	OverdueScheduler
@Date			:	13 October 2019
@Description	:	Scheduler To send  email alert and add fine for Overdue books
@Developer		:	Nitin Chandwani
*/
public class OverdueBatch implements Database.Batchable<Sobject> {
    
    private String query, status;
    
    public OverdueBatch(){
        status = Label.OverdueStatus;
        query = 'SELECT Employee__c, Employee__r.Email From Borrowing_History__c ';
        query += 'WHERE Status__c =:status  AND Due_Date__c >= TODAY';
    }
    
    public Database.QueryLocator start( Database.BatchableContext bc ){
        return Database.getQueryLocator( query );
    }
    public void execute( Database.BatchableContext bc, List<Borrowing_History__c> borrowingHistories ){
        if( borrowingHistories != NULL && borrowingHistories.size() > 0 ){
            List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
            Id templateId = getEmailTemplateId( 'Overdue_Reminder' );
            if( templateId != NULL ){
                for( Borrowing_History__c borrowingHistory : borrowingHistories ){
                    borrowingHistory.Fine__c = 10;
                    if( String.isNotBlank( borrowingHistory.Employee__r.Email ) ){
                        Messaging.SingleEmailMessage email = generateEmail( templateId, borrowingHistory );
        				if( email != NULL ) emails.add( email );
                    }
                }
                Database.update( borrowingHistories, false );
                if( emails != NULL && emails.size() > 0 ){
                    Messaging.sendEmail( emails );
                }
            }
        }
    }
	public void finish( Database.BatchableContext bc ){
        
    }
    
    private Messaging.SingleEmailMessage generateEmail( Id templateId, Borrowing_History__c borrowingHistory ){
        Messaging.SingleEmailMessage email;
        if( templateId != NULL && borrowingHistory != NULL){
            email = new Messaging.SingleEmailMessage();
            email.setTargetObjectId( borrowingHistory.Employee__c );
            email.setSaveAsActivity( true );
            email.setWhatId( borrowingHistory.Id );
            email.setTemplateId( templateId );
        }
        return email;
    }
    
    //Get Email Template
    private static Id getEmailTemplateId( String templateName ){
        if( String.isNotBlank( templateName ) ){
            List<EmailTemplate> emailTemplates = [SELECT Id FROM EmailTemplate WHERE DeveloperName  =: templateName ];
            if( emailTemplates != NULL && emailTemplates.size() > 0 ){
                return emailTemplates[0].Id;
            }
        }
        return NULL;
    }
}