force-app/main/default/objects/Borrowing_History__c/Borrowing_History__c.object-meta.xml
<CustomObject>
    <label>Borrowing History</label>
    <nameField>
        <displayFormat>BH-{00000}</displayFormat>
        <label>Borrowing History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Borrowing Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Borrowing_History__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Borrowing Histories</relationshipLabel>
    <relationshipName>Borrowing_Histories</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Borrowing_History__c/fields/Fine__c.field-meta.xml
<CustomField>
    <fullName>Fine__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fine(If Any)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Borrowing_History__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Borrowing Histories</relationshipLabel>
    <relationshipName>Borrowing_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Borrowing_History__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( ISNULL(Return_Date__c ), &#39;Borrowed&#39;, &#39;Returned&#39;)</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <displayFormat>ITM-{000000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Borrowable_Days__c.field-meta.xml
<CustomField>
    <fullName>Borrowable_Days__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Borrowable Days</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Current_Borrower__c.field-meta.xml
<CustomField>
    <fullName>Current_Borrower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Borrower</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Borrowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BorrowItemsController.cls
/**
 @Name			:		BorrowItemsController
 @Date			:		08 October 2019
 @Developer		:		Nitin Chandwani
 @Description	:		Controller to fetch, upsert data for borrow Items controller
*/
public class BorrowItemsController {
    
	@AuraEnabled
    public static Item__c getItem( String itemCode ){
        if( String.isNotBlank( itemCode ) ){
            List<Item__c> items = [SELECT Id, Name, Item_Name__c, RecordType.Name, Borrowable_Days__c, Status__c FROM Item__c WHERE Name =: itemCode LIMIT 1];
            if( items != NULL && items.size() > 0  ){
                return items[0];
            }
        }
        return NULL;
    }
    
    @AuraEnabled
    public static List<Borrowing_History__c> getBorrowingHistory( String employeeId ){
        if( String.isNotBlank( employeeId ) ){
            return [SELECT Id, Employee__c, Issue_Date__c, Item__r.Name, Item__r.Item_Name__c, Due_Date__c FROM Borrowing_History__c WHERE Employee__c =: employeeId AND Status__c = 'Borrowed'];
        }
        return NULL;
    }
    
    @AuraEnabled
    public static boolean createBorrowingHistory( String employeeId, List<Item__c> items ){
        if( String.isNotBlank( employeeId ) && items != NULL && items.size() > 0 ){
            List<Borrowing_History__c> borrowingHistories =  new List<Borrowing_History__c>();
            for( Item__c item : items ){
                item.Status__c = 'Borrowed';
                item.Current_Borrower__c = employeeId;
                //Borrow Item
                Borrowing_History__c borrowingHistory = new Borrowing_History__c();
                borrowingHistory.Employee__c = employeeId;
                borrowingHistory.Issue_Date__c = System.today();
                borrowingHistory.Fine__c = 0;
                borrowingHistory.Item__c = item.Id;
                if( item.Borrowable_Days__c != NULL ){
                    borrowingHistory.Due_Date__c = borrowingHistory.Issue_Date__c + (Integer)item.Borrowable_Days__c;
                }
                borrowingHistories.add( borrowingHistory );
            }
            if( borrowingHistories != NULL ){
                Savepoint sv = Database.setSavepoint();
                try{
                    INSERT borrowingHistories;
                    UPDATE items;
                    return TRUE;
                }catch( Exception excep ){
                    Database.rollback( sv );
                }
            }
        }
        return FALSE;
    }
	@AuraEnabled
    public static boolean returnItems( List<Borrowing_History__c> borrowingHistories ){
        if( borrowingHistories != NULL && borrowingHistories.size() > 0 ){
            List<Item__c> items =  new List<Item__c>();
            for( Borrowing_History__c borrowingHistory : borrowingHistories ){
                borrowingHistory.Return_Date__c = System.today();
            }
            Savepoint sv = Database.setSavepoint();
            try{
                UPDATE borrowingHistories;
                return TRUE;
            }catch( Exception excep ){
                Database.rollback( sv );
            }
        }
        return false;
    }    
    
    @AuraEnabled
    public static List<Item__c> searchItems( String keyword ){
        if( String.isNotBlank( keyword ) ){
            keyword = '%' + keyword + '%';
            return [SELECT Id, Name, Item_Name__c, RecordType.Name, 
                    Borrowable_Days__c, Status__c FROM Item__c WHERE ( Name LIKE: keyword OR
                   	Item_Name__c LIKE: keyword OR RecordType.Name LIKE: keyword ) AND 
                   	Status__c = 'Available' ];
        }
        return NULL; 
    }
}