force-app/main/default/objects/Borrowing_History__c/Borrowing_History__c.object-meta.xml
<CustomObject>
    <label>Borrowing History</label>
    <nameField>
        <displayFormat>BH-{00000}</displayFormat>
        <label>Borrowing History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Borrowing Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Borrowing_History__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Borrowing Histories</relationshipLabel>
    <relationshipName>Borrowing_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Borrowing_History__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( ISNULL(Return_Date__c ), &#39;Borrowed&#39;, &#39;Returned&#39;)</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <displayFormat>ITM-{000000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Borrowable_Days__c.field-meta.xml
<CustomField>
    <fullName>Borrowable_Days__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Borrowable Days</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Borrowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item__c/recordTypes/Book.recordType-meta.xml
<RecordType>
    <fullName>Book</fullName>
    <active>true</active>
    <label>Book</label>
</RecordType>

force-app/main/default/classes/TestBorrowItemsController.cls
@isTest
public class TestBorrowItemsController {

    @TestSetup
    public static void dataSetup(){
        //Insert employeess
        List<Contact> contacts = new List<Contact>();
        for( Integer i = 0; i < 5 ; i ++ ){
            Contact con = new Contact();
            con.LastName  = 'Test ' + i ;
            contacts.add( con );
        }
        INSERT contacts;
        //Insert Items
        List<Item__c> items = new List<Item__c>();
        for( Integer i = 0; i < 10 ; i ++ ){
            //Books
            Item__c book = new Item__c();
            book.Item_Name__c = 'Book ' + i;
            book.Borrowable_Days__c = 5;
            book.Status__c = 'Available';
            book.RecordTypeId = Schema.SObjectType.Item__c.getRecordTypeInfosByName().get('Book').getRecordTypeId();
            items.add( book );
            //AV Equipments
            Item__c avEquipments = new Item__c();
            avEquipments.Item_Name__c = 'AV Equipments ' + i;
            avEquipments.Borrowable_Days__c = 5;
            avEquipments.Status__c = 'Available';
            avEquipments.RecordTypeId = Schema.SObjectType.Item__c.getRecordTypeInfosByName().get('AV Equipment').getRecordTypeId();
            items.add( avEquipments );
        }
        INSERT items;
    }
    @isTest
    public static void unitTest1(){
        
        
        //Get Borrowing History
        List<Borrowing_History__c> borrowingHistories = BorrowItemsController.getBorrowingHistory( '' );
        System.assertEquals( NULL, borrowingHistories);
        Contact con = [SELECT Id FROM Contact LIMIT 1];
        borrowingHistories = BorrowItemsController.getBorrowingHistory( con.Id );
        //get Item
        Item__c item = BorrowItemsController.getItem('TEST');
        System.assertEquals( NULL, item);
        Item__c tempItem = [SELECT Name FROM Item__c WHERE RecordType.Name = 'Book' LIMIT 1 ];
        Item__c item1 = BorrowItemsController.getItem( tempItem.Name );
        System.assertEquals( tempItem.Id, item1.Id);
        tempItem = [SELECT Name FROM Item__c WHERE RecordType.Name = 'AV Equipment' LIMIT 1 ];
        Item__c item2 = BorrowItemsController.getItem( tempItem.Name );
        System.assertEquals( tempItem.Id, item2.Id);
        //Borrow Item
        BorrowItemsController.createBorrowingHistory( '', NULL );
        BorrowItemsController.createBorrowingHistory( con.Id , NULL );
        Boolean result = BorrowItemsController.createBorrowingHistory( con.Id , new List<Item__c>{item1, item2});
        System.assertEquals( TRUE, result );
        //Prevent Borrowing Same item
        BorrowItemsController.createBorrowingHistory( con.Id , new List<Item__c>{item1, item2});
        
        //Return Item
        borrowingHistories = BorrowItemsController.getBorrowingHistory( con.Id );
        System.assertEquals( 2, borrowingHistories.size() );
        BorrowItemsController.returnItems( borrowingHistories );
        
        //Search Items
        BorrowItemsController.searchItems( '' );
        List<Item__c> searchResult = BorrowItemsController.searchItems( 'Book' );
        System.assertEquals( 10, searchResult.size() );
    }
}